CREATE TABLE INNOV.MLS2_SITES
(
    "SITE_ID" RAW(16) NOT NULL ENABLE,
	"SITE_NAME" VARCHAR2(10 BYTE),
	"DESCN" VARCHAR2(50 BYTE),
	"TRANS_TS" TIMESTAMP (6) DEFAULT systimestamp,
	"MOD_BY_ID" NUMBER,
	"DB_LINK_NAME" VARCHAR2(50 BYTE)
);

alter table "INNOV"."MLS2_SITES" add constraint MLS2_SITES_SITE_ID_PK primary key("SITE_ID");
alter table "INNOV"."MLS2_SITES" add constraint MLS2_SITES_SITE_NAME_UK unique("SITE_NAME");

COMMENT ON TABLE "INNOV"."MLS2_SITES"  IS 'MLS2 sites are STRATIS(CLNC, BIC, CPEN, MCBH, KNSR/OKI)';

--GRANT SELECT, INSERT, UPDATE, DELETE ON "INNOV"."MLS2_SITES" TO "STRAT_COMMON_APP_ROLE";