#!/bin/sh 

source ./defaultExports.sh

# Script Default Values when starting Tomcat, which should be
# overridden when starting the container as needed.
#
DEFAULT_MLS2_ENVIRONMENT_MAIL_HOST="1.2.3.4"
DEFAULT_MLS2_ENVIRONMENT_SPRING_PROFILE="prod,integration_enterprise"
DEFAULT_MLS2_ENVIRONMENT_DATABASE_CONNECTION="jdbc:oracle:thin:@//innov-dbs:1521/"
DEFAULT_STRATIS_COMMON_DB_DATASOURCE_PASSWORD="ENC(sLurzxCf4Eh1UZM1zvrF4wFjl8aXve50)"
DEFAULT_STRATIS_COMMON_DB_FLYWAY_PASSWORD="ENC(sLurzxCf4Eh1UZM1zvrF4wFjl8aXve50)"
DEFAULT_MLS2_ENVIRONMENT_BROKER_URL="tcp://mips-messaging-server:61611"
DEFAULT_MLS2_ENVIRONMENT_CACHE_CLUSTER_ADDRESS="mips-caching-server"

###ADF SETTINGS
DEFAULT_STRATIS_DB_LOGIN_TIMEOUT="10"
DEFAULT_STRATIS_DB_POOL_INITIAL_SIZE="3"
DEFAULT_STRATIS_DB_POOL_MIN_SIZE="2"
DEFAULT_STRATIS_DB_POOL_MAX_SIZE="50"
DEFAULT_STRATIS_DB_POOL_INACTIVE_TIMEOUT="120"
DEFAULT_STRATIS_DB_POOL_MAX_CX_REUSE_TIME="300"
DEFAULT_STRATIS_DB_POOL_VALIDATE_CX_ON_BORROW="true"
DEFAULT_STRATIS_DB_POOL_MAX_STATEMENTS="10"
DEFAULT_STRATIS_BIC_DB_PASSWORD="ENC(sLurzxCf4Eh1UZM1zvrF4wFjl8aXve50)"
DEFAULT_STRATIS_MCBH_DB_PASSWORD="ENC(sLurzxCf4Eh1UZM1zvrF4wFjl8aXve50)"
DEFAULT_STRATIS_OKI_DB_PASSWORD="ENC(sLurzxCf4Eh1UZM1zvrF4wFjl8aXve50)"
DEFAULT_STRATIS_ESD_DB_PASSWORD="ENC(sLurzxCf4Eh1UZM1zvrF4wFjl8aXve50)"
DEFAULT_STRATIS_CLNC_DB_PASSWORD="ENC(sLurzxCf4Eh1UZM1zvrF4wFjl8aXve50)"
DEFAULT_STRATIS_CPEN_DB_PASSWORD="ENC(sLurzxCf4Eh1UZM1zvrF4wFjl8aXve50)"

export MLS2_ENVIRONMENT_MAIL_HOST="${MLS2_ENVIRONMENT_MAIL_HOST-$DEFAULT_MLS2_ENVIRONMENT_MAIL_HOST}"
export MLS2_ENVIRONMENT_SPRING_PROFILE="${MLS2_ENVIRONMENT_SPRING_PROFILE-$DEFAULT_MLS2_ENVIRONMENT_SPRING_PROFILE}"
export MLS2_ENVIRONMENT_DATABASE_CONNECTION="${MLS2_ENVIRONMENT_DATABASE_CONNECTION-$DEFAULT_MLS2_ENVIRONMENT_DATABASE_CONNECTION}"
export STRATIS_COMMON_DB_DATASOURCE_PASSWORD="${STRATIS_COMMON_DB_DATASOURCE_PASSWORD-$DEFAULT_STRATIS_COMMON_DB_DATASOURCE_PASSWORD}"
export STRATIS_COMMON_DB_FLYWAY_PASSWORD="${STRATIS_COMMON_DB_FLYWAY_PASSWORD-$DEFAULT_STRATIS_COMMON_DB_FLYWAY_PASSWORD}"
export MLS2_ENVIRONMENT_BROKER_URL="${MLS2_ENVIRONMENT_BROKER_URL-$DEFAULT_MLS2_ENVIRONMENT_BROKER_URL}"
export MLS2_ENVIRONMENT_CACHE_CLUSTER_ADDRESS="${MLS2_ENVIRONMENT_CACHE_CLUSTER_ADDRESS-$DEFAULT_MLS2_ENVIRONMENT_CACHE_CLUSTER_ADDRESS}"

###ADF SETTINGS
export STRATIS_DB_LOGIN_TIMEOUT="${STRATIS_DB_LOGIN_TIMEOUT-$DEFAULT_STRATIS_DB_LOGIN_TIMEOUT}"
export STRATIS_DB_POOL_INITIAL_SIZE="${STRATIS_DB_POOL_INITIAL_SIZE-$DEFAULT_STRATIS_DB_POOL_INITIAL_SIZE}"
export STRATIS_DB_POOL_MIN_SIZE="${STRATIS_DB_POOL_MIN_SIZE-$DEFAULT_STRATIS_DB_POOL_MIN_SIZE}"
export STRATIS_DB_POOL_MAX_SIZE="${STRATIS_DB_POOL_MAX_SIZE-$DEFAULT_STRATIS_DB_POOL_MAX_SIZE}"
export STRATIS_DB_POOL_INACTIVE_TIMEOUT="${STRATIS_DB_POOL_INACTIVE_TIMEOUT-$DEFAULT_STRATIS_DB_POOL_INACTIVE_TIMEOUT}"
export STRATIS_DB_POOL_MAX_CX_REUSE_TIME="${STRATIS_DB_POOL_MAX_CX_REUSE_TIME-$DEFAULT_STRATIS_DB_POOL_MAX_CX_REUSE_TIME}"
export STRATIS_DB_POOL_VALIDATE_CX_ON_BORROW="${STRATIS_DB_POOL_VALIDATE_CX_ON_BORROW-$DEFAULT_STRATIS_DB_POOL_VALIDATE_CX_ON_BORROW}"
export STRATIS_DB_POOL_MAX_STATEMENTS="${STRATIS_DB_POOL_MAX_STATEMENTS-$DEFAULT_STRATIS_DB_POOL_MAX_STATEMENTS}"
export STRATIS_BIC_DB_PASSWORD="${STRATIS_BIC_DB_PASSWORD-$DEFAULT_STRATIS_DB_PASSWORD}"
export STRATIS_OKI_DB_PASSWORD="${STRATIS_OKI_DB_PASSWORD-$DEFAULT_STRATIS_DB_PASSWORD}"
export STRATIS_ESD_DB_PASSWORD="${STRATIS_ESD_DB_PASSWORD-$DEFAULT_STRATIS_DB_PASSWORD}"
export STRATIS_MCBH_DB_PASSWORD="${STRATIS_MCBH_DB_PASSWORD-$DEFAULT_STRATIS_DB_PASSWORD}"
export STRATIS_CLNC_DB_PASSWORD="${STRATIS_CLNC_DB_PASSWORD-$DEFAULT_STRATIS_DB_PASSWORD}"
export STRATIS_CPEN_DB_PASSWORD="${STRATIS_CPEN_DB_PASSWORD-$DEFAULT_STRATIS_DB_PASSWORD}"

export JAVA_OPTS="$JAVA_OPTS -Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl -Djavax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl -Djavax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl -Djavax.xml.datatype.DatatypeFactory=com.sun.org.apache.xerces.internal.jaxp.datatype.DatatypeFactoryImpl"

#enforced default exports, can not be overridden
export STRATIS_LOG_PATH="/data/logs/application"
export MLS2_ENV_AJP_ENABLED="false"
export STRATIS_BARCODE_IMAGE_PATH="/data/storage/local/barcode/img"
export STRATIS_UCP_JOB_ENABLED="true"
export STRATIS_I009_JOB_ENABLED="true"

echo "MLS2 Environment Mail Host (MLS2_ENVIRONMENT_MAIL_HOST): $MLS2_ENVIRONMENT_MAIL_HOST"
echo "MLS2 Environment Spring Profile (MLS2_ENVIRONMENT_SPRING_PROFILE): $MLS2_ENVIRONMENT_SPRING_PROFILE"
echo "STRATIS DB Url (MLS2_ENVIRONMENT_DATABASE_CONNECTION): $MLS2_ENVIRONMENT_DATABASE_CONNECTION"
echo "STRATIS_COMMON Datasource Password (MIGS_DB_DATASOURCE_PASSWORD): $STRATIS_COMMON_DB_DATASOURCE_PASSWORD"
echo "STRATIS_COMMON Flyway Database Password (MIGS_DB_FLYWAY_PASSWORD): $STRATIS_COMMON_DB_FLYWAY_PASSWORD"
echo "Broker URL (MLS2_ENVIRONMENT_BROKER_URL): ${MLS2_ENVIRONMENT_BROKER_URL}"
echo "MLS2_ENVIRONMENT_CACHE_CLUSTER_ADDRESS: ${MLS2_ENVIRONMENT_CACHE_CLUSTER_ADDRESS}"

###ADF SETTINGS
echo "Database Login Timeout (STRATIS_DB_LOGIN_TIMEOUT): $STRATIS_DB_LOGIN_TIMEOUT"
echo "Connection Pool Initial Size (STRATIS_DB_POOL_INITIAL_SIZE): $STRATIS_DB_POOL_INITIAL_SIZE"
echo "Connection Pool Minimum Size (STRATIS_DB_POOL_MIN_SIZE): $STRATIS_DB_POOL_MIN_SIZE"
echo "Connection Pool Maximum Size (STRATIS_DB_POOL_MAX_SIZE): $STRATIS_DB_POOL_MAX_SIZE"
echo "Connection Pool Inactive Timeout (STRATIS_DB_POOL_INACTIVE_TIMEOUT): $STRATIS_DB_POOL_INACTIVE_TIMEOUT"
echo "Connection Pool Maximum Connection Reuse Time (STRATIS_DB_POOL_MAX_CX_REUSE_TIME): $STRATIS_DB_POOL_MAX_CX_REUSE_TIME"
echo "Connection Pool Validation Connection on Borrow (STRATIS_DB_POOL_VALIDATE_CX_ON_BORROW): $STRATIS_DB_POOL_VALIDATE_CX_ON_BORROW"
echo "Connection Pool Max Statements (STRATIS_DB_POOL_MAX_STATEMENTS): $STRATIS_DB_POOL_MAX_STATEMENTS"
echo "STRATIS_CPEN_DB_PASSWORD: $STRATIS_CPEN_DB_PASSWORD"
echo "STRATIS_CLNC_DB_PASSWORD: $STRATIS_CLNC_DB_PASSWORD"
echo "STRATIS_BIC_DB_PASSWORD: $STRATIS_BIC_DB_PASSWORD"
echo "STRATIS_OKI_DB_PASSWORD: $STRATIS_OKI_DB_PASSWORD"
echo "STRATIS_ESD_DB_PASSWORD: $STRATIS_ESD_DB_PASSWORD"
echo "STRATIS_MCBH_DB_PASSWORD: $STRATIS_MCBH_DB_PASSWORD"

/wait && /opt/app/tomcat/current/bin/catalina.sh run
