
-- This file includes an example of disabling the password complexity and lifetime restrictions on a STRATIS DB user account.

SELECT PROFILE FROM DBA_USERS WHERE USERNAME = 'STRATIS';
-- assumes result: STRAT_USER_PROFILE

ALTER PROFILE DEFAULT LIMIT PASSWORD_VERIFY_FUNCTION NULL;
ALTER PROFILE STRAT_USER_PROFILE LIMIT PASSWORD_VERIFY_FUNCTION NULL;

ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;
ALTER PROFILE STRAT_USER_PROFILE LIMIT PASSWORD_LIFE_TIME UNLIMITED;

SELECT LIMIT FROM DBA_PROFILES WHERE PROFILE = 'STRAT_USER_PROFILE' AND RESOURCE_NAME = 'PASSWORD_VERIFY_FUNCTION';
ALTER USER STRATIS IDENTIFIED BY "webacct#X2013X#" ACCOUNT UNLOCK;
