
-- Currently the intention is for the ACTIVEMQ account and schema to reside in the ****STRATIS COMMON**** database.

-- Creates the ACTIVEMQ Oracle user/schema
CREATE USER ACTIVEMQ IDENTIFIED BY "webacct#X2013X#";
GRANT CONNECT TO ACTIVEMQ;
GRANT CONNECT, RESOURCE, DBA TO ACTIVEMQ;
GRANT CREATE SESSION to ACTIVEMQ;
GRANT UNLIMITED TABLESPACE TO ACTIVEMQ;
GRANT ALL PRIVILEGES TO ACTIVEMQ;
